### ISSUE TITLE
NPM package includes unused files creating big package size

### ISSUE THREAD

**Issue by easingthemes** [quicoto/two-way-data-binding#49]
NPM package:
Unpacked Size -> 58.6 kB
Total Files -> 18

Update `npmignore` or use `files` property https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files

### Steps to reproduce
Install the package and check content, or create a tarball `npm pack` and unzip locally
### Expected behaviour
Only necessary files are included in npm package.

### Actual behaviour
A lot of unused files, eg test files, are included

#### Sample Code that illustrates the problem
<img width="234" alt="Screenshot 2023-07-12 at 11 31 00" src="https://github.com/quicoto/two-way-data-binding/assets/2750284/49e324b3-6a7f-496c-bf94-0c65190688c5">
<img width="343" alt="Screenshot 2023-07-12 at 11 36 02" src="https://github.com/quicoto/two-way-data-binding/assets/2750284/e0892c04-225a-4f43-880e-192c3a4d2200">

**Comment by quicoto** [comment]
Thank you so much @easingthemes !
